
name: build

on:
  push:
    paths:
      - '!.**'
      - '!**'
      - '.github/workflows/build.yml'
      - '**.h'
      - '**.c'
      - '**.cpp'
      - '**.ac'
      - 'Makefile**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-image:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: |
          cd ${{ github.workspace }}
          autoscan
          aclocal
          autoconf
          autoheader
          touch NEWS AUTHORS README ChangeLog
          automake --add-missing
          automake
          ./configure
          make
